version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: "Install Dependencides"
          command: gem install bundler:2.1.4 && bundle install
      - run:
          name: "Rubocop"
          command: bundle exec rubocop
      - run:
          name: "RSpec"
          command: bundle exec rspec
          environment:
            SS4_ENDPOINT: "https://scholarsphere-rmd-api.dsrd.libraries.psu.edu/api/v1"
      - run:
          name: "Copy VCR Logs"
          when: on_fail
          command: cp vcr.log /tmp/vcr.log
      - run:
          name: "Upload Coverage"
          when: on_success
          command: |
            wget -q https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -O cc-test-reporter
            chmod 755 cc-test-reporter
            export TAG=${CIRCLE_SHA1}
            export GIT_COMMIT_SHA=$CIRCLE_SHA1
            export GIT_BRANCH=$CIRCLE_BRANCH
            export GIT_COMMITED_AT=$(git log -1 --date=short --pretty=format:%ct)
            ./cc-test-reporter after-build -d
      - store_artifacts:
          path: /tmp/vcr.log
          destination: VCR
